"""Schemas for recommendation responses and AI outputs."""

from typing import List

from pydantic import BaseModel


class RecommendationItem(BaseModel):
    """Single recommendation entry returned to clients."""

    itemId: int
    score: float
    reason: str


class RecommendationsResponse(BaseModel):
    """Recommendation response payload for the API."""

    items: List[RecommendationItem]


class AIRecommendationItem(BaseModel):
    """Individual recommendation entry generated by the AI model."""

    itemId: int
    score: float
    reason: str


class AIRecommendationResult(BaseModel):
    """Structured AI output parsed via LangChain."""

    items: List[AIRecommendationItem]
